version: '2'
 
services:
  web1:
    build:
      context:  ./web1
      dockerfile: Dockerfile  
    volumes:
      - web_volumes:/usr/local/apache2/htdocs

  web2:
    build:
      context:  ./web2
      dockerfile: Dockerfile  
    volumes:
      - web_volumes:/usr/local/apache2/htdocs

  web3:
    build:
      context:  ./web3
      dockerfile: Dockerfile
    volumes:
      - web_volumes:/usr/local/apache2/htdocs
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - nginx_volumes:/etc/nginx/nginx_volumes

volumes:
    web_volumes:
    
    nginx_volumes:
